services:
  backend:
    build:
      context: ./app-gestion
    ports:
      - "3000:3000"
    volumes:
      - ./app-gestion:/usr/src/app
      - /usr/src/app/node_modules  
    command: npm start

  frontend:
    build:
      context: ./projet-virtu
    ports:
      - "8080:80"
    volumes:
      - /usr/src/app/node_modules
    command: serve -s dist -l 80  
